### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by emtek995** [coderlore/todo-mvc-auth-local#12]
In order to implement the routes/endpoints we need a well defined API that the front end can use.
We need at the least:

- create message
- delete message
- like message
- edit message
- get all messages

Any other ideas are welcome.

**Comment by coderlore** [comment]
I know we all talked about this, but capture it here as well. For the edit and delete message, only the currently logged-in user should have the ability to edit and delete their message only.

For the like message, are we only doing likes/up-vote for now and then adding a down-vote feature later?

**Comment by emtek995** [comment]
Look like this is all figured out now.
